# Словарь с названиями валют
currency_names = {
    # Основные фиатные валюты
    "USD": "Доллар США",
    "EUR": "Евро",
    "GBP": "Фунт стерлингов",
    "JPY": "Японская иена",
    "CNY": "Китайский юань",
    "RUB": "Российский рубль",
    "CAD": "Канадский доллар",
    "AUD": "Австралийский доллар",
    "CHF": "Швейцарский франк",
    "KRW": "Корейская вона",
    "INR": "Индийская рупия",
    "BRL": "Бразильский реал",
    "MXN": "Мексиканское песо",
    "SGD": "Сингапурский доллар",
    "HKD": "Гонконгский доллар",
    "NOK": "Норвежская крона",
    "SEK": "Шведская крона",
    "DKK": "Датская крона",
    "PLN": "Польский злотый",
    "CZK": "Чешская крона",
    "HUF": "Венгерский форинт",
    "TRY": "Турецкая лира",
    "ZAR": "Южноафриканский рэнд",
    "THB": "Тайский бат",
    "MYR": "Малайзийский ринггит",
    "PHP": "Филиппинское песо",
    "IDR": "Индонезийская рупия",
    "VND": "Вьетнамский донг",
    "TWD": "Тайваньский доллар",
    "NZD": "Новозеландский доллар",
    "ILS": "Израильский шекель",
    "AED": "Дирхам ОАЭ",
    "SAR": "Саудовский риял",
    "EGP": "Египетский фунт",
    "QAR": "Катарский риал",
    "KWD": "Кувейтский динар",
    "BHD": "Бахрейнский динар",
    "OMR": "Оманский риал",
    "JOD": "Иорданский динар",
    "LBP": "Ливанский фунт",
    "UAH": "Украинская гривна",
    "BYN": "Белорусский рубль",
    "KZT": "Казахстанский тенге",
    "UZS": "Узбекский сум",
    "KGS": "Киргизский сом",
    "TJS": "Таджикский сомони",
    "AMD": "Армянский драм",
    "AZN": "Азербайджанский манат",
    "GEL": "Грузинский лари",
    "MDL": "Молдавский лей",
    "BTC": "Биткоин",
    "ETH": "Эфириум",
    "USDT": "Тезер",
    "USDC": "Монета Доллар США",
    "BNB": "Монета Байнанс",
    "XRP": "Риппл",
    "ADA": "Кардано",
    "SOL": "Солана",
    "DOGE": "Догкоин",
    "DOT": "Полкадот",
    "MATIC": "Полигон",
    "SHIB": "Сиба Ину",
    "LTC": "Лайткоин",
    "BCH": "Биткоин Кэш",
    "AVAX": "Avalanche",
    "ATOM": "Cosmos",
    "LINK": "Chainlink",
    "UNI": "Uniswap",
    "XLM": "Stellar",
    "ALGO": "Algorand",
    "VET": "VeChain",
    "ICP": "Internet Computer",
    "FIL": "Filecoin",
    "HBAR": "Hedera",
    "NEAR": "NEAR Protocol",
    "FLOW": "Flow",
    "MANA": "Decentraland",
    "SAND": "The Sandbox",
    "AXS": "Axie Infinity",
    "CHZ": "Chiliz",
    "ENJ": "Enjin Coin",
    "BAT": "Basic Attention Token",
    "ZEC": "Zcash",
    "DASH": "Dash",
    "XTZ": "Tezos",
    "EOS": "EOS",
    "THETA": "Theta Network",
    "FTM": "Fantom",
    "AAVE": "Aave",
    "COMP": "Compound",
    "MKR": "Maker",
    "SNX": "Synthetix",
    "CRV": "Curve DAO Token",
    "SUSHI": "SushiSwap",
    "YFI": "yearn.finance",
    "1INCH": "1inch",
    "UMA": "UMA",
    "BAL": "Balancer",
    "REN": "Ren",
    "KNC": "Kyber Network Crystal",
    "LRC": "Loopring",
    "ZRX": "0x",
    "STORJ": "Storj",
    "GRT": "The Graph",
    "BAND": "Band Protocol",
    "OMG": "OMG Network",
    "SKL": "SKALE Network",
    "NMR": "Numeraire",
    "ANT": "Aragon",
    "BNT": "Bancor",
    "MLN": "Melon",
    "REP": "Augur",
    "KRL": "Kryll",
    "OCEAN": "Ocean Protocol",
    "FETCH": "Fetch.ai",
    "NU": "NuCypher",
    "KEEP": "Keep Network",
    "NKN": "NKN",
    "OGN": "Origin Protocol",
    "CTX": "Cryptex Finance",
    "MASK": "Mask Network",
    "TRU": "TrueFi",
    "AUDIO": "Audius",
    "API3": "API3",
    "BADGER": "Badger DAO",
    "FARM": "Harvest Finance",
    "ALPHA": "Alpha Finance Lab",
    "RARI": "Rarible",
    "SUPER": "SuperFarm",
    "TRB": "Tellor",
    "ALCX": "Alchemix",
    "FORTH": "Ampleforth Governance Token",
    "TRIBE": "Tribe",
    "FEI": "Fei USD",
    "RAI": "Rai Reflex Index",
    "FOX": "ShapeShift FOX Token",
    "INDEX": "Index Cooperative",
    "MPL": "Maple",
    "POOL": "PoolTogether",
    "BOND": "BarnBridge",
    "CREAM": "Cream Finance",
    "COVER": "Cover Protocol",
    "HEGIC": "Hegic",
    "PICKLE": "Pickle Finance",
    "ROOK": "KeeperDAO",
    "TORN": "Tornado Cash",
    "PERP": "Perpetual Protocol",
    "DYDX": "dYdX",
    "IMX": "Immutable X",
    "LPT": "Livepeer",
    "RENDER": "Render Token",
    "JASMY": "JasmyCoin",
    "GALA": "Gala",
    "ENS": "Ethereum Name Service",
    "APE": "ApeCoin",
    "GMT": "STEPN",
    "GST": "Green Satoshi Token",
    "LOOKS": "LooksRare",
    "OP": "Optimism",
    "ARB": "Arbitrum",
    "BLUR": "Blur",
    "PEPE": "Pepe",
    "FLOKI": "Floki Inu",
    "BONK": "Bonk",
    "WIF": "dogwifhat",
    "POPCAT": "Popcat",
    "MOODENG": "Moo Deng",
    "PNUT": "Peanut the Squirrel",
    "GOAT": "Goatseus Maximus",
    "FARTCOIN": "Fartcoin",
    "CHILLGUY": "Chill Guy",
    "PENGU": "Pudgy Penguins",
    "HYPE": "Hyperliquid",
    "VIRTUAL": "Virtual Protocol",
    "AI16Z": "ai16z",
    "ZEREBRO": "Zerebro",
    "GRIFFAIN": "Griffain",
    "LUCE": "Luce",
    "KOMA": "Koma Inu",
    "MIRA": "Mira",
    "USUAL": "Usual",
    "MOVE": "Movement",
    "ME": "Magic Eden",
    "ONDO": "Ondo Finance",
    "ENA": "Ethena",
    "ETHFI": "Ether.fi",
    "REZ": "Renzo",
    "EIGEN": "EigenLayer",
    "PENDLE": "Pendle",
    "JUP": "Jupiter",
    "WEN": "Wen",
    "JTO": "Jito",
    "PYTH": "Pyth Network",
    "TIA": "Celestia",
    "SEI": "Sei",
    "SUI": "Sui",
    "APT": "Aptos",
    "OP": "Optimism",
    "ARB": "Arbitrum",
    "STRK": "Starknet",
    "BLAST": "Blast",
    "MODE": "Mode",
    "MANTA": "Manta Network",
    "ALT": "AltLayer",
    "DYM": "Dymension",
    "PIXEL": "Pixels",
    "PORTAL": "Portal",
    "AEVO": "Aevo",
    "METIS": "Metis",
    "MEME": "Memecoin",
    "WLD": "Worldcoin",
    "ORDI": "ORDI",
    "SATS": "1000SATS",
    "RATS": "RATS",
    "TOSHI": "Toshi",
    "DEGEN": "Degen",
    "BOME": "BOOK OF MEME",
    "SLERF": "Slerf",
    "MYRO": "Myro",
    "SMOG": "Smog",
    "JUPITER": "Jupiter",
    "DRIFT": "Drift Protocol",
    "TNSR": "Tensor",
    "W": "Wormhole",
    "EZ": "Renzo Restaked ETH",
    "OMNI": "Omni Network",
    "SAGA": "Saga",
    "TAO": "Bittensor",
    "NEAR": "NEAR Protocol",
    "FET": "Fetch.ai",
    "AGIX": "SingularityNET",
    "OCEAN": "Ocean Protocol",
    "RNDR": "Render Token",
    "GRT": "The Graph",
    "LPT": "Livepeer",
    "THETA": "Theta Network",
    "TFUEL": "Theta Fuel",
    "AKRO": "Akropolis",
    "NMR": "Numeraire",
    "CTSI": "Cartesi",
    "STORJ": "Storj",
    "ANKR": "Ankr",
    "SKL": "SKALE Network",
    "CVC": "Civic",
    "REQ": "Request Network",
    "QNT": "Quant",
    "HOLO": "Holo",
    "ICX": "ICON",
    "ZIL": "Zilliqa",
    "ONT": "Ontology",
    "QTUM": "Qtum",
    "WAVES": "Waves",
    "LSK": "Lisk",
    "STRAT": "Stratis",
    "ARK": "Ark",
    "KMD": "Komodo",
    "DCR": "Decred",
    "SC": "Siacoin",
    "DGB": "DigiByte",
    "RVN": "Ravencoin",
    "MONA": "MonaCoin",
    "VTC": "Vertcoin",
    "XVG": "Verge",
    "DOGE": "Dogecoin",
    "SHIB": "Shiba Inu",
    "ELON": "Dogelon Mars",
    "AKITA": "Akita Inu",
    "KISHU": "Kishu Inu",
    "HOKK": "Hokkaido Inu",
    "LEASH": "Doge Killer",
    "BONE": "Bone ShibaSwap"
}